### ISSUE TITLE
Question: When will the plugin be available?

### ISSUE THREAD

**Issue by FlorianLautenschlager** [Kong/kong-plugin-zipkin#1]
... and with which versions of Kong is it compatible?

Thx for you work!

**Comment by james-callahan** [comment]
> When will the plugin be available

Our hope is that it will be in the mid-may release (0.14) as a "preview" plugin.

> which versions of Kong is it compatible?

This plugin currently needs some changes to the kong core to operate; hence it doesn't work with any version of kong until https://github.com/Kong/kong/pull/3434 is merged.

**Comment by FlorianLautenschlager** [comment]
Ok. Thx for your fast response. Looking forward to a release of the plugin ;-)
