### ISSUE TITLE
Loud logging at the moment.

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong-plugin-zipkin#112]
Just enabled this bad boy back on our Kong clusters and noticed a heckin bunch of stdout of kong.log warnings:

```
 [warn] 88#0: *465011 [kong] tracing_headers.lua:408 [zipkin] Mismatched header types. conf: w3c. found: b3, 
```

Derives from here:
https://github.com/Kong/kong-plugin-zipkin/blob/master/kong/plugins/zipkin/tracing_headers.lua#L408

Be that we don't really control what clients pass to a gateway, and we wanted to simply enable this plugin globally maybe it makes sense to use this more as a debug statement as you can standardize around how you want your headers and what to expect but clients will do what clients do. Thoughts on changing the log level away from warn, I usually think a warning as an actionable item that requires attention but it really can't be in this case.

I would think:
```
kong.log.info()
kong.log.debug()
```

Would be sufficient to help with the discovery of client passing other headers differently than the Zipkin plugin was configured to handle. Otherwise I may just write a patch to comment this line out at live deployments as its just filling our stdout with a log thats more or less undesired as we run kong in ```notice``` mode. 

Other ideas(just as a side tangent) is this plugin could parse the headers it sees from clients and figure out what trace values the client personally wants to use when logging to the zipkin endpoint as well based on what the clients give it vs setting a "hard" use XYZ value. Not that we wanna use that because we intend to standardize with w3c BUT it would be a neat way to handle it anyways as a setting, maybe a "derive" header from client toggle on/off that will render the other conf hard settings unused and the plugin just goes with the flow of what the client gave it if detected otherwise no headers detected leads to just defaulting to the configured ones. Just an idea.

**Comment by kikito** [comment]
Hello @jeremyjpj0916! Would setting the `header_type` to `preserve` be an acceptable compromise to you? That setting does not generate logs when it encounters a "mismatch".

**Comment by jeremyjpj0916** [comment]
Ah yes, re-reviewing the config this setup makes enough sense. Don't think a code change is really needed, yeah will close this, gonna go with this:
```
  "config": {
    "header_type": "preserve",
    "sample_ratio": 0.05,
    "http_endpoint": "http://zipkin-http-collector.company.com:9411/api/v2/spans",
    "default_service_name": "StargateStageCore",
    "traceid_byte_count": 16,
    "default_header_type": "w3c",
    "tags_header": "Zipkin-Tags",
    "include_credential": false,
    "static_tags": null
  },
```

Thanks @kikito good shout, was just rushing the impl without fully studying the docs/fields better 😆  .
