### ISSUE TITLE
A question about processed time of a request in Kong

### ISSUE THREAD

**Issue by mrpk1906** [Kong/kong-plugin-zipkin#117]
![](https://i.imgur.com/Ls6zZ0S.png)

Hello everybody,
Im trying to trace latency of my service.

In image above, I saw `kaf` is 2ms, `khs` is 124ms
So, what does Kong do in time from 2ms ==> 124ms?

Thanks!

**Comment by kikito** [comment]
`kaf` is the `kong access finished`. It means that Kong has stopped "preprocessing the request" and is about to send it upstream.
`khs` is `kong header filter started`. That's when Kong has received the upstream response and is starting to send it back to the end user.

The 124ms time is representing the time it takes for the request to travel from Kong to the upstream server and back.

* If Kong is physically separated from the upstream server, try to move it closer (ideally, to the same box)
* It could be that the communication is fast but the the Upstream server itself consumes 124ms just to process a request. In that case your best option would be to ... make it faster. It really depends on what your upstream server is doing in that case.
