### ISSUE TITLE
**unknown-service-name** when integrate with Jaeger 

### ISSUE THREAD

**Issue by bnlong4417** [Kong/kong-plugin-zipkin#12]
No service name in UI Jaeger with spans from kong-plugin-zipkin.

Screenshot:
<img width="1680" alt="screen shot 2018-07-03 at 12 04 41 pm" src="https://user-images.githubusercontent.com/24292696/42199558-500e765e-7eb9-11e8-8a21-4c3d6f24bc60.png">

**Comment by james-callahan** [comment]
Is this because we [don't currently send `localEndpoint`](https://github.com/Kong/kong-plugin-zipkin/blob/60587178e03594a8608959a03c8e5a4009333710/kong/plugins/zipkin/reporter.lua#L49)?

Possible information here: https://github.com/jaegertracing/jaeger/issues/585

**Comment by james-callahan** [comment]
Yes it is. providing 
```lua
localEndpoint = {
	serviceName = "myservice";
};
```

**Comment by bnlong4417** [comment]
👍
