### ISSUE TITLE
Latency missing

### ISSUE THREAD

**Issue by subnetmarco** [Kong/kong-plugin-zipkin#20]
When using the zipkin plugin, I am seeing traces like:

<img width="1602" alt="screen shot 2018-08-17 at 3 17 03 pm" src="https://user-images.githubusercontent.com/964813/44291059-c5796f80-a230-11e8-8c85-f0a120d3fed3.png">

I am not seeing any latency value for the `access`, `balancer`, etc spans - is this intended?

**Comment by james-callahan** [comment]
That is expected if the access/balancer phases took a negligible (i.e. `0`) amount of time (which is common depending on choice of plugins).
Also keep in mind that kong only rarely updates the time via [`ngx.update_time`](https://github.com/openresty/lua-nginx-module/#ngxupdate_time). This was improved in https://github.com/Kong/kong/commit/a08ff0cb07d06ab955fec1981aae0c75246889b1

**Comment by thefosk** [comment]
@james-callahan wouldn't the latency still be there, with value `0` ? It seems like it's actually missing completely.

**Comment by james-callahan** [comment]
If you enlarge the span it should be there (as 0).
