### ISSUE TITLE
Feature request: Add supporting for "uber-trace-id" header.

### ISSUE THREAD

**Issue by longit644** [Kong/kong-plugin-zipkin#22]
When using Kong Zipkin plugin with Jaeger client without `B3TextMapCodec`, Jaeger can't aggregate spans and services span:

<img width="1250" alt="screen shot 2018-10-09 at 6 31 59 am" src="https://user-images.githubusercontent.com/24292696/46639024-04230a80-cb8e-11e8-816b-84be88a359ba.png">

To flexibility support integrating multiple tracing system (jaeger, zipkin) with Kong. 
Let's support extracting span from Tracing Context header like `uber-trace-id` header when unable extracting from `X-B3-...` headers in the request, and also injecting Kong's span context to `uber-trace-id` as well as current `X-B3-...` headers to upstream request headers.

**Comment by james-callahan** [comment]
I'd like to have the option of different propagation formats (see also #21): to make the change I think we may need to break up the plugin into multiple plugins where you separately enable extractors, injectors and reporters.

To make coordination between these different plugins consistent, I'm looking into if we should add things to the Kong PDK.

**Comment by Roberttmoon** [comment]
Is there any news on this? We use Jeager tracing and while we can collect the Zipkin trace from kong, we are having a bear of a time aggregating the traces together. It would be awesome to find out if theres any news on this issue.

**Comment by wpjunior** [comment]
Hi!, my team at Globo.com have some troubles to use this plugin, the default behavior of many applications is to use `uber-trace-id`, @gszr and @kikito how could we improve this plugin to achieve this feature?

**Comment by jcchavezs** [comment]
This is the kon-plugin-zipkin, isn't it better to request this in an opentracing plugin or create a plugin for Jaeger? I honestly don't think this plugin should support such a thing.

**Comment by kikito** [comment]
This was implemented in #101
