### ISSUE TITLE
Use "kong" or get service name from env variable or config.

### ISSUE THREAD

**Issue by longit644** [Kong/kong-plugin-zipkin#23]
When I use Kong Zipkin plugins, the list of services in tracer dashboard is polluted with many services.

I think, we should to get service name from env variable (ex: `KONG_ZIPKIN_PLUGIN_SERVICE_NAME`), or add to config or just "kong".

**Comment by james-callahan** [comment]
> When I use Kong Zipkin plugins, the list of services in tracer dashboard is polluted with many services.

Doesn't it end up being the same as the number of services that you have in Kong?
Why is this a problem? Wouldn't you want to drill down into per-service latencies?

>  just "kong" at here

We already set "kong" as the 'component'.

**Comment by bnlong4417** [comment]
> Doesn't it end up being the same as the number of services that you have in Kong?
If I use the same service name for spans in Kong service and in my service, it's difficult to get how many spans in Kong, how many spans in my service and their latency. 
If I use a service name for spans in Kong service and another in my service, there are many services appearing in the list of services in tracer dashboard, so it's difficult to manage them.

> Wouldn't you want to drill down into per-service latencies?
No no, I really want it. But I want more details.

**Comment by secat** [comment]
@james-callahan any update on this feature request?
