### ISSUE TITLE
Integrate kong-plugin-zipkin with openresty

### ISSUE THREAD

**Issue by duckty** [Kong/kong-plugin-zipkin#26]
Hi,

I am using openresty as API gateway because I need to write a custom lua script to integrate with our authorization backend. I couldn't find any lua plugin supporting zipkin except kong-plugin-zipkin. I installed it in openresty but I don't know how to configure it with openresty.

If you know how to do it, please give me the instruction.

Thanks,
cua dong

**Comment by james-callahan** [comment]
kong-plugin-zipkin is a plugin for the Kong API gateway; which adds lots of top of plain openresty.
Our recent releases bundle this zipkin plugin.
I welcome you to try out Kong, perhaps start at https://konghq.com/install/

Closing the issue as this isn't something we can action in the repository.
We try and answer questions about Kong over at http://discuss.konghq.com/
