### ISSUE TITLE
Plugin throws lua stacktrace errors on endpoints leveraging request termination plugin

### ISSUE THREAD

**Issue by jeremyjpj0916** [Kong/kong-plugin-zipkin#32]
Lua stacktrace:

```
2018/12/12 16:04:04 [error] 238#0: *2313102 failed to run log_by_lua*: .../local/share/lua/5.1/kong/plugins/zipkin/opentracing.lua:174: attempt to perform arithmetic on field 'KONG_ACCESS_ENDED_AT' (a nil value)
stack traceback:
	.../local/share/lua/5.1/kong/plugins/zipkin/opentracing.lua:174: in function 'log'
	/usr/local/share/lua/5.1/kong/plugins/zipkin/handler.lua:34: in function 'log'
	/usr/local/share/lua/5.1/kong/init.lua:529: in function 'log'
log_by_lua(nginx.conf:150):2: in function <log_by_lua(nginx.conf:150):1> while logging request, client: 10.119.116.11, server: kong, request: "GET /F5/status HTTP/1.1", host: "edge-kong-gateway-stage.****-***-***.company.com"
```

Just need to anticipate that field being null occasionally I suppose and maybe set that value to -1 or 0 of some sort(HTTP Log plugin takes a similar approach on endpoints that don't actually route or fail to proxy).

**Comment by rsbrisci** [comment]
For a little additional context, the route this is error is for uses the request termination plugin.

**Comment by james-callahan** [comment]
This should have been fixed back in October with 174737f2e47177d2d9d7d01921cd488407140eda.
What version are you running?

**Comment by jeremyjpj0916** [comment]
I think @rsbrisci just set it as an environment variable, and maybe it came bundled with 0.14.1 in that case? If so I can force a luarocks install on it and get the latest that way. Will give that a go, thx.

**Comment by jeremyjpj0916** [comment]
@james-callahan

Seems to be the case(to run log_by_lua*: ...lugin_zipkin**_0_0_4_0**-kong/plugins/zipkin/opentracing.lua), trying to add a luarocks install to overwrite it adds this to my build, first time I have seen of this msg before:
```
Step 22/38 : RUN luarocks install kong-plugin-zipkin
 ---> Running in 745db4762940

Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/local/bin/luarocks with sudo, you may want sudo's -H flag.
Installing https://luarocks.org/kong-plugin-zipkin-0.1.1-0.src.rock 
Will not remove kong-plugin-zipkin 0.0.4-0.
Removing it would break dependencies for: 
kong 0.14.1-0

Use --force to force removal (warning: this may break modules).
Failed removing.
kong-plugin-zipkin 0.1.1-0 is now installed in /usr/local (license: Apache 2.0)

Checking stability of dependencies in the absence of
kong-plugin-zipkin 0.0.4-0...
```

Would it be okay to --force remove under these circumstances?

https://github.com/Kong/kong/blob/master/kong-0.14.1-0.rockspec#L39

Maybe this ^  is the issue, since the Kong release bundled it and includes an early iteration in the rockspec?

**Comment by jeremyjpj0916** [comment]
But yeah I see how I could probs pathwork around to get newest one running on 0.14.1 but not worth the time since 1.0 is close by. will just deploy latest on that, hopefully they are decoupled now xD .
