### ISSUE TITLE
Can zipkin collect data through kafka?

### ISSUE THREAD

**Issue by HefeiJoe** [Kong/kong-plugin-zipkin#46]
With high concurrency, zipkin loses data
![image](https://user-images.githubusercontent.com/27885579/63509205-2c012f80-c50e-11e9-8247-c3f8bd827bc2.png)
![image](https://user-images.githubusercontent.com/27885579/63509232-3de2d280-c50e-11e9-9d4c-e1702ae1a35c.png)

**Comment by adriancole** [comment]
similar question asked on the other issue. zipkin is mostly a dumb proxy. lost data is almost always elasticsearch queue overflow errors. unless you can carefully tune elasticsearch, enable storage throttling https://github.com/openzipkin/zipkin/tree/master/zipkin-server#throttled-storage-experimental

**Comment by adriancole** [comment]
also make sure you are sampling.. if you are doing 100% sampling with no rate-limit you can overwhelm any storage. Rate limiter is the best kind of sampler

**Comment by shakuzen** [comment]
To make this issue relevant to this repository, perhaps it could be refocused as "can the kong-plugin-zipkin report spans to Zipkin via Kafka?" From the Zipkin Server side, it can [collect spans via Kafka](https://github.com/openzipkin/zipkin/tree/master/zipkin-server#kafka-collector). I'm not sure if this plugin supports reporting spans to Kafka or not, though. If not, this could be an enhancement request.

**Comment by HefeiJoe** [comment]
> To make this issue relevant to this repository, perhaps it could be refocused as "can the kong-plugin-zipkin report spans to Zipkin via Kafka?" From the Zipkin Server side, it can [collect spans via Kafka](https://github.com/openzipkin/zipkin/tree/master/zipkin-server#kafka-collector). I'm not sure if this plugin supports reporting spans to Kafka or not, though. If not, this could be an enhancement request.

I thought about whether I could get kong's data through kafka. I set the environment variable KAFKA_BOOTSTRAP_SERVERS of zipkin, but felt no improvement.I guess kong's data is still sent over HTTP
Now, my question is how to transfer kong's data to zipkin through kafka
![image](https://user-images.githubusercontent.com/27885579/63559905-63132780-c586-11e9-9936-6531a6099d99.png)
This is my expected architecture diagram
![image](https://user-images.githubusercontent.com/27885579/63560694-85f30b00-c589-11e9-825a-36775c27ce7b.png)
I don't know if KAFKA_BOOTSTRAP_SERVERS are configured in the environment variable, so zipkin can collect data through kafka

**Comment by HefeiJoe** [comment]
> To make this issue relevant to this repository, perhaps it could be refocused as "can the kong-plugin-zipkin report spans to Zipkin via Kafka?" From the Zipkin Server side, it can [collect spans via Kafka](https://github.com/openzipkin/zipkin/tree/master/zipkin-server#kafka-collector). I'm not sure if this plugin supports reporting spans to Kafka or not, though. If not, this could be an enhancement request.

Yes, I have the same doubts.

**Comment by adriancole** [comment]
there is no kafka code here. so yes this would be a new feature, and likely not that difficult to write if someone knows lua.
