### ISSUE TITLE
Numerous data problems

### ISSUE THREAD

**Issue by adriancole** [Kong/kong-plugin-zipkin#49]
Hi. We had to make some changes in our UI to accommodate numerous data problems from Kong. If looking at this pull request https://github.com/openzipkin/zipkin/pull/2834 or our api docs https://zipkin.io/zipkin-api/#/default/post_spans isn't clear what's wrong, please reach out to gitter so we can help increase the usability of this plugin.

https://gitter.im/openzipkin/zipkin

**Comment by kikito** [comment]
Hi, I've touched Zipkin only tangentially so far but I am attempting to understand and fix what's needed.

As a first step, I've added comments in https://github.com/openzipkin/zipkin/pull/2834.
