### ISSUE TITLE
Connections in dependency graph, should it be like this?

### ISSUE THREAD

**Issue by Igor-lkm** [Kong/kong-plugin-zipkin#53]
My apologies if this is expected behaviour 🎩 

My setup:

1) **Create service on Kong**
- name: `gateway-service-a`
- url `http://service-a:3000`, 
2) **Kong: Add zipkin plugin to this service.**
- default service name: `kong-gateway`
3) **Service A: node.js koa app with `zipkin-instrumentation-koa`** (traces incoming HTTP requests)
- localServiceName: `service-a`

Dependency, which would be created on http request, looks like:

```
gateway-service-a ----- service-a
```

So we can add more services, and we would get:
```
gateway-service-a ----- service-a
gateway-service-b ----- service-b

Goes to this pattern:
{service-name-on-kong} ----- {localServiceName}
```

What I would expect in graph (both services are connect to Kong, not services on Kong):

```
      kong-gateway  ------ service-a
            |
        service-b
```

Or even better:

```
      kong-gateway ------ gateway-service-a  ------ service-a
            |
      gateway-service-b
            |
        service-b
```

Even trace looks like this in UI:

<img width="414" alt="Screenshot 2019-10-30 at 17 03 56" src="https://user-images.githubusercontent.com/6287367/67876134-b29e4280-fb37-11e9-8995-74ada9592220.png">

`kong-gateway` directly to `service-a`. You have `gateway-service-a` when you would open `service-a` span

So the questing is should it be 
`{service-name-on-kong} ----- {localServiceName}`  
or 
`{kong-gateway} ----- {localServiceName}`
or
`{kong-gateway} ----- {service-name-on-kong} -----  {localServiceName}`
?

Thank you!

**Comment by jcchavezs** [comment]
@Igor-lkm there have been changed in the tags and endpoints (see #55). Would you recheck if this is still an issue?

**Comment by Igor-lkm** [comment]
@jcchavezs that was more a question or discussion rather than an issue. 

> For all the spans created by the plugin, the localEndpoint is now { serviceName = "kong" }

That sounds reasonable. 

I think the issue might be closed. Thank you!
