### ISSUE TITLE
Which plugin version for Kong 1.1.2?

### ISSUE THREAD

**Issue by msummers-nr** [Kong/kong-plugin-zipkin#73]
I've been asked to back-port Victor  Soares' code to Kong 1.1.2, would that correspond to kong-plugin-zipkin version 0.1.2?

**Comment by hishamhm** [comment]
Yes, the version of kong-plugin-zipkin in Kong 1.1.2 is 0.1.2. The review for PR #69 is ongoing and we hope to get it merged on the next release of the plugin.
