### ISSUE TITLE
Incorrect timestamps on Kong phase start/end logs in Jaeger UI

### ISSUE THREAD

**Issue by OmriHarary** [Kong/kong-plugin-zipkin#85]
I currently have Kong and some backend services shipping spans in Zipkin format to the Zipkin-compatible endpoint on a Jaeger all-in-one instance, all running in Kubernetes and using the Kong Kubernetes Ingress Controller. For the most part everything is working, except the offset timestamps for the phase start/end logs viewed in the UI are all set to huge negative numbers that indicate the beginning of the epoch. See image below:
<img width="515" alt="Screen Shot 2020-05-26 at 3 44 44 PM" src="https://user-images.githubusercontent.com/18216913/82943684-03f4a000-9f68-11ea-82aa-81fe4a2c1945.png">

Zipkin-formatted spans received by the same endpoint from other sources correctly indicate the log time relative to the start of the trace:
<img width="378" alt="Screen Shot 2020-05-26 at 4 11 07 PM" src="https://user-images.githubusercontent.com/18216913/82945958-87fc5700-9f6b-11ea-9b0d-beafc46e0c4f.png">

Any assistance with this matter would be greatly appreciated.

Environment:
Kong Image: `kong:2.0`
Ingress Controller Image: `kong-docker-kubernetes-ingress-controller.bintray.io/kong-ingress-controller:0.8.0`
Jaeger Image: `jaegertracing/all-in-one:1.18.0`

**Comment by kikito** [comment]
Hi, apologies for the late reply. I just noticed your Kong version:

> `kong:2.0`

This version of kong uses an older version of the zipkin plugin (v0.2.0). The problem you are experiencing was known and solved in #71, but that bugfix is only available in the zipkin plugin v1.0.0. You have several options:

* updating to kong 2.1 (which is currently in beta)
* updating the zipkin plugin version of your kong 2.0 rockspec file to a newer version of the plugin (1.0.0 or above).

**Comment by OmriHarary** [comment]
Oh, excellent. Thank you @kikito, I don't know why I didn't see that PR when I was looking before creating this issue. I am not currently in a position to take either of those options, but I will be waiting for the 2.1 release for the resolution.
I will close this issue at this time.

**Comment by OmriHarary** [comment]
This issue has been closed for a while, but for posterity: I have finally been able to test with a newer Kong release and I can confirm that this is no longer an issue.
