### ISSUE TITLE
Feature request: Set dynamic tags through request headers

### ISSUE THREAD

**Issue by secat** [Kong/kong-plugin-zipkin#97]
We would like to be able to inject dynamically tags based on the request headers, i.e. be able to configure the plugin to select pre-defined request headers and inject them as tags inside spans.

Does this sound to you as a neat feature?

> **NOTE** It will probably look like the following PR: **feat(handler) static tags** #84

**Comment by jcchavezs** [comment]
This is definitively a nice feature to have. We have in some of the zipkin tracers.

**Comment by kikito** [comment]
Implemented in #102
